import { FadeUp, GlowOrb, GoldDivider } from '../components/ui'

const SECTIONS = [
  {
    num: '1',
    title: 'Agreement to Terms',
    content: `By accessing or using the Soft Strategy Desk™ ("the Tool"), you agree to be bound by these Terms of Use. If you do not agree, please do not use the Tool. These Terms apply to all users, including visitors, free users, and paying customers.`,
  },
  {
    num: '2',
    title: 'Description of the Tool',
    content: `The Soft Strategy Desk™ is an AI-assisted clarity and strategy tool designed to help women navigate workplace challenges, content creation, life decisions, and business building. It is powered by Claude, an AI model developed by Anthropic. The Tool includes four engines: Corporate Survival, Content-to-Cash, Decision Clarity, and Soft Business Builder.`,
  },
  {
    num: '3',
    title: 'Not Professional Advice',
    intro: 'The Soft Strategy Desk™ provides AI-generated content for informational and organizational purposes only.',
    items: [
      'Corporate Survival Engine: Does not provide legal advice. Consult a licensed employment attorney for matters involving discrimination, wrongful termination, or legal action.',
      'Decision Clarity Engine: Does not provide financial, psychological, or mental health advice. Consult a licensed professional for major decisions.',
      'Soft Business Builder Engine: Does not guarantee business outcomes or income. Results will vary.',
      'Content-to-Cash Engine: Does not guarantee engagement, sales, or revenue.',
    ],
    note: 'Tae Adams Studio is not liable for any decisions made or actions taken based on content generated by the Tool.',
  },
  {
    num: '4',
    title: 'AI-Generated Content',
    intro: 'Outputs are generated by Claude (Anthropic). By using the Tool, you acknowledge that:',
    items: [
      'AI-generated content may contain errors or inaccuracies',
      'You are responsible for reviewing all outputs before use',
      'Content quality depends on the accuracy of your inputs',
      'Tae Adams Studio does not guarantee outputs are complete, accurate, or suitable for your situation',
    ],
  },
  {
    num: '5',
    title: 'Intellectual Property',
    blocks: [
      {
        label: 'Our Content',
        text: 'The Soft Strategy Desk™, including its design, frameworks (Soft System™, AI Energy Twin™, Energy-First Branding™), branding, copy, and underlying prompts, is the intellectual property of Tae Adams Studio. All rights reserved.',
      },
      {
        label: 'Your Content',
        text: 'Your inputs remain yours. You grant Tae Adams Studio a limited license to process your inputs solely to generate your requested outputs. We do not use your inputs to train AI models.',
      },
      {
        label: 'Generated Outputs',
        text: 'Outputs are provided for your personal and professional use. AI-generated content is not eligible for copyright protection in the United States under current law.',
      },
    ],
  },
  {
    num: '6',
    title: 'Acceptable Use',
    intro: 'You agree not to use the Tool to:',
    items: [
      'Submit false, misleading, or deceptive information',
      'Harass, threaten, or harm any individual or group',
      'Generate content for illegal purposes',
      'Circumvent or interfere with the Tool\'s security features',
      'Scrape, reverse engineer, or extract the Tool\'s underlying prompts',
      'Resell or sublicense access without written permission',
    ],
  },
  {
    num: '7',
    title: 'Free Access and Email Collection',
    content: `Access to the full Tool requires providing a valid email address. By submitting your email, you consent to receive marketing communications, confirm you are 18 or older, and agree to our Privacy Policy. You may unsubscribe at any time.`,
  },
  {
    num: '8',
    title: 'Purchases and Refunds',
    intro: 'Digital products and paid sessions are sold through Stan Store.',
    items: [
      'Digital products: All sales are final unless otherwise stated at point of purchase.',
      'Coaching sessions: Cancellations more than 24 hours before a scheduled session may be eligible for rescheduling. No-shows are non-refundable.',
      'Refund requests: Contact tadams0622@icloud.com within 7 days of purchase. We will review in good faith.',
    ],
  },
  {
    num: '9',
    title: 'Disclaimers and Limitation of Liability',
    content: `The Soft Strategy Desk™ is provided "as is" without warranties of any kind. To the fullest extent permitted by law, Tae Adams Studio shall not be liable for any indirect, incidental, special, or consequential damages. Our total liability shall not exceed the amount you paid in the 30 days preceding the claim, or $50, whichever is greater.`,
  },
  {
    num: '10',
    title: 'Indemnification',
    content: `You agree to indemnify and hold harmless Tae Adams Studio, its owner, contractors, and affiliates from any claims, damages, or expenses arising from your use of the Tool or violation of these Terms.`,
  },
  {
    num: '11',
    title: 'Governing Law',
    content: `These Terms are governed by the laws of the State of Delaware. Any disputes shall be resolved in the courts of the State of Delaware.`,
  },
  {
    num: '12',
    title: 'Changes',
    content: `We may update these Terms from time to time. Continued use after changes constitutes acceptance.`,
  },
  {
    num: '13',
    title: 'Contact',
    content: `Tae Adams Studio · tadams0622@icloud.com · Delaware`,
  },
]

export default function TermsOfUse() {
  return (
    <main className="min-h-screen bg-plum-900 pt-24">
      {/* Hero */}
      <section className="relative py-20 px-5 overflow-hidden">
        <GlowOrb color="lavender" size={500} opacity={0.09} className="-top-10 left-1/2 -translate-x-1/2" />
        <div className="relative z-10 max-w-2xl mx-auto text-center">
          <FadeUp>
            <p className="font-mono text-[13px] tracking-widest text-gold uppercase mb-5">Legal</p>
            <h1 className="font-serif text-[clamp(36px,7vw,60px)] font-light leading-[1] tracking-[-0.02em] mb-6 text-ink">
              Terms of Use
            </h1>
            <div className="flex flex-wrap justify-center gap-x-6 gap-y-1">
              {[
                'Effective: May 1, 2026',
                'Updated: May 1, 2026',
                'Tae Adams Studio · Delaware',
              ].map(m => (
                <span key={m} className="font-sans text-xs text-ink-dim">{m}</span>
              ))}
            </div>
          </FadeUp>
        </div>
      </section>

      {/* Content */}
      <section className="pb-28 px-5">
        <div className="max-w-2xl mx-auto">
          <GoldDivider className="m-14" />

          <div className="space-y-12">
            {SECTIONS.map(s => (
              <FadeUp key={s.num}>
                <div className="flex gap-5 items-start">
                  <span className="font-mono text-[13px] text-gold tracking-widest pt-1 w-6 flex-shrink-0">{s.num.padStart(2, '0')}</span>
                  <div className="flex-1">
                    <h2 className="font-serif text-xl font-semibold text-ink mb-4">{s.title}</h2>

                    {'intro' in s && s.intro && (
                      <p className="font-sans text-sm text-ink-soft leading-relaxed mb-4 italic">{s.intro}</p>
                    )}

                    {'content' in s && s.content && (
                      <p className="font-sans text-sm text-ink-soft leading-relaxed">{s.content}</p>
                    )}

                    {'blocks' in s && s.blocks && (
                      <div className="space-y-5">
                        {s.blocks.map(b => (
                          <div key={b.label}>
                            <p className="font-sans text-xs font-semibold text-ink uppercase tracking-wide mb-2">{b.label}</p>
                            <p className="font-sans text-sm text-ink-soft leading-relaxed">{b.text}</p>
                          </div>
                        ))}
                      </div>
                    )}

                    {'items' in s && s.items && (
                      <ul className="space-y-1.5">
                        {s.items.map(item => (
                          <li key={item} className="font-sans text-sm text-ink-soft leading-relaxed flex gap-2">
                            <span className="text-gold/50 mt-1.5 flex-shrink-0">—</span>
                            {item}
                          </li>
                        ))}
                      </ul>
                    )}

                    {'note' in s && s.note && (
                      <p className="font-sans text-sm text-ink-soft leading-relaxed mt-4 italic border-l-2 border-gold/30 pl-4">
                        {s.note}
                      </p>
                    )}
                  </div>
                </div>
              </FadeUp>
            ))}
          </div>

          <GoldDivider className="mt-14 mb-8" />
          <p className="font-sans text-xs text-ink-dim text-center">Last updated: May 1, 2026</p>
        </div>
      </section>
    </main>
  )
}
